name: Continuous-Integration

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  Build-Test-Report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      if: ${{ success() }}
      run: dotnet build --configuration Release --no-restore --verbosity normal

    - name: Test
      if: ${{ success() }}
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal  --collect:'XPlat Code Coverage' --settings coverlet.runsettings
    - name: Report Coverage
      if: ${{ success() }}
      uses: codecov/codecov-action@v1.0.10
   
    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'vintagegamestudio'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4d2e69bf38e04c4caeb669090bf0e893 }}
        package: ${{env.DOTNET_ROOT}}/myapp 